language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7
install:
  - composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - phpunit -c tests/phpunit.xml.dist || exit 1

after_script:
  - php vendor/bin/coveralls -v
